#!/bin/csh
#
# Copyright 2006-2007, by the California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
#
# This software is subject to U. S. export control laws and regulations
# (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
# is subject to U.S. export control laws and regulations, the recipient has
# the responsibility to obtain export licenses or other export authority as
# may be required before exporting such information to foreign countries or
# providing access to foreign nationals.


# C Shell script that allows easy execution of the Validation Tool (VTool)
# without the need to set the CLASSAPTH or having to type in that long java
# command (java gov.nasa.pds.tools.VTool ...)

# Set to the location of the product-tools jar file

set jarpath = "/home/user/product-tools-0.5.0/bin/product-tools-0.5.0-app.jar"

# Executes VTool via the executable jar file
# Arguments are passed in to the tool via 'argv'

java -jar $jarpath $argv

